-- J2Commerce 6.0.0 Initial Release
-- This file serves as the schema version marker for Joomla's extension update tracking
-- No SQL needed for initial installation as install.mysql.utf8.sql handles table creation
